variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "AMPLITUDE_LOGIN_EVENT_URL" {}
variable "ASSISTANT_ID" {}
variable "ASSISTANT_URL" {}
variable "COOKIE_DOMAIN" {}
variable "ENCRYPTION" {}
variable "ENV" {}
variable "GOAL_SUBMISSION_WINDOW_LENGTH" {}
variable "MONGODB_DB_NAME" {}
variable "MONGODB_URL" {}
variable "OPENAI_API_KEY" {}
variable "BUILD_BUCKET_NAME" {}
variable "STAGE_NAME" {}
variable "CERTIFICATE_ARN" {}
variable "POPULATE_DB_ENUMS" {}
variable "SECRET_KEY" {}
variable "SEND_EMAIL_URL" {}
variable "UI_URL" {}
variable "ACCESS_KEY_AWS" {}
variable "SECRET_KEY_AWS" {}
variable "REGION_AWS" {}
variable "AMPLITUDE_API_KEY" {}
variable "BUCKET_FOLDER_NAME" {}
variable "BUCKET_NAME" {}
variable "US_EAST_1_CERTIFICATE_ARN" {}
variable "SMART_GOALS_ASSISTANT_ID" {}
variable "OPENAI_MODEL" {}