variable "BUILD_BUCKET_NAME" {}
variable "AMPLITUDE_LOGIN_EVENT_URL" {}
variable "ASSISTANT_ID" {}
variable "ASSISTANT_URL" {}
variable "COOKIE_DOMAIN" {}
variable "ENCRYPTION" {}
variable "ENV" {}
variable "GOAL_SUBMISSION_WINDOW_LENGTH" {}
variable "MONGODB_DB_NAME" {}
variable "MONGODB_URL" {}
variable "OPENAI_API_KEY" {}
variable "POPULATE_DB_ENUMS" {}
variable "SECRET_KEY" {}
variable "SEND_EMAIL_URL" {}
variable "UI_URL" {}
variable "ACCESS_KEY_AWS" {}
variable "SECRET_KEY_AWS" {}
variable "REGION_AWS" {}
variable "AMPLITUDE_API_KEY" {}
variable "AUTH_IAM_ROLE_ARN" {}
variable "BUCKET_FOLDER_NAME" {}
variable "BUCKET_NAME" {}
variable "SMART_GOALS_ASSISTANT_ID" {}
variable "OPENAI_MODEL" {}